version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "22:40"
    open-pull-requests-limit: 1
    versioning-strategy: "increase"
    allow:
      - dependency-name: "flet*"

    groups:
      flet:
        applies-to: version-updates
        patterns:
          - "flet*"
